config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users

  root 'welcome#index'

  get "/users/:id/images/feed" => "images#feed", as: :feed
  get "/hashtag/:hash" => "images#hash", as: :hashtag

  resources :users do
    resources :images do 
      resources :comments
    end
  end

  resources :followlinks

  get "/allusers" => "users#index", as: :allusers

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :image
  belongs_to :user
end

app/models/followlink.rb
class Followlink < ActiveRecord::Base
	belongs_to :user
	belongs_to :followee, :class_name => "User"

end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
	has_and_belongs_to_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :large => "1000x1000#",:medium => "400x400#", :thumb => "150x150#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :comments
  has_and_belongs_to_many :hashtags

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
  has_many :comments

  has_many :followlinks
  has_many :followees, through: :followlinks

   has_many :inverse_followlinks, class_name: "Followlink", foreign_key: :followee_id
  has_many :followers, through: :inverse_followlinks, source: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def new
  	@image = Image.find(params[:image_id])
  	@comment = @image.comments.new
  	@comment.user = current_user
  end

  def create
  	@image = Image.find(params[:image_id])

  	data = comment_params
  	data[:user] = current_user

  	@comment = @image.comments.build(data)
  	@comment.save
  	redirect_to user_image_path(current_user, @image)
  end

  def edit
  	@comment = Comment.find(params[:id])
  end

  def update
  	@comment = Comment.find(params[:id])
  	@comment.update(comment_params)
	redirect_to user_image_path(current_user, @comment.image)  	
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy
  	redirect_to user_image_path(current_user, @comment.image)  	
  end

  private
  def comment_params
  	params.require(:comment).permit(:body)
  end
end

app/controllers/followlinks_controller.rb
class FollowlinksController < ApplicationController
  def create
  	@followlink = current_user.followlinks.build(followee_id: params[:followee_id])
  	@followlink.save
  	redirect_to allusers_path
  end

  def destroy
  	@followlink = current_user.followlinks.find(params[:id])
  	@followlink.destroy
  	redirect_to allusers_path
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @images = @user.images
  end

  def feed
    @images = current_user.images
    current_user.followees.each do |followee|
      @images+=followee.images
    end
    @images
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = current_user.images.new

  end

  def create
    @image = current_user.images.build(image_params)
    hashtags @image.caption
    @image.save
    redirect_to user_image_path(current_user, @image)

  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    @image.update(image_params)
    hashtags @image.caption
    redirect_to user_image_path(current_user,@image)
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to feed_path(current_user)


  end

  def hash
    @hashtagText = params[:hash]
    hashtag = Hashtag.find_by(hashtag: @hashtagText)
    @images = hashtag.images

  end

  def image_params
    params.require(:image).permit(:caption, :public, :image)
  end

  def hashtags(caption)
    letterArr = caption.split("")
    hashFound = false
    hash = ""
    letterArr.each_with_index do |letter, index|
      if hashFound && letter!=" " && letter!="#"
        hash << letter

      end
      if hashFound && (letter == " "||letter=="#"||index==(letterArr.length-1))
        hashFound = false
        if Hashtag.where(hashtag: hash).count == 0

          @hashtag = @image.hashtags.new(hashtag: hash)
          @hashtag.save
        else
          @hashtag = Hashtag.where(hashtag: hash).first
          if !@image.hashtags.include?(@hashtag)
            @image.hashtags << (@hashtag)
          end
        end

        hash = ""
      end
      if letter == "#"
        hashFound = true
      end
    end



  end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :authenticate_user!, except: [:index]
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followlinks_helper.rb
module FollowlinksHelper
end

app/helpers/images_helper.rb
module ImagesHelper
	def captionSend image
		caption = image.caption+" "
		image.hashtags.each do |hashtag|
			caption = caption.gsub("#"+hashtag.hashtag+" ", (link_to "#"+hashtag.hashtag+" ", "/hashtag/#{hashtag.hashtag}"))
			caption = caption.gsub("#"+hashtag.hashtag+"#", (link_to "#"+hashtag.hashtag+"#", "/hashtag/#{hashtag.hashtag}"))
		end
		
		caption = caption[0..caption.length-1]
		caption.html_safe
	end

	def show image

	if image.user != current_user
		if image.read_attribute(:public)
			return true	
		end 
	elsif current_user == image.user
		return true
	else
		return false
    end
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div class="item  animated bounceInRight row">

      <div  class="col-sm-6 col-sm-offset-3">
      <p><%= comment.body %>
      <% if comment.user == current_user %><br>
		<%= link_to "edit", edit_user_image_comment_path(current_user, comment.image, comment) %>
		<%= link_to "delete", user_image_comment_path(current_user, comment.image, comment), method: :delete, data: {confirm: "Are you sure, bru?"} %>

		<% end %>
      </p>
      <span><%= comment.user.username %></span>
      </div>
      </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [current_user, @comment.image, @comment], html: { class: "col-md-6 col-md-offset-3"} do |f| %>
<%= f.input :body %>
<%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<% @path = user_image_comment_path(current_user, @comment.image, @comment) %>
<%= render "form" %>

app/views/comments/new.html.erb
<% @path = user_image_comments_path %>
<%= render "form" %>

app/views/followlinks/create.html.erb
<h1>Followlinks#create</h1>
<p>Find me in app/views/followlinks/create.html.erb</p>

app/views/followlinks/destroy.html.erb
<h1>Followlinks#destroy</h1>
<p>Find me in app/views/followlinks/destroy.html.erb</p>

app/views/images/_form.html.erb
<%= simple_form_for [current_user, @image],html: { class: "col-md-6 col-md-offset-3"} do |f| %>

<%= f.input :caption %>
<%= f.input :public %>
<%= f.input :image, as: :file %>

<%= f.button :submit %>

<% end %>

app/views/images/_image.html.erb
<% if show(image) %>


<% if @size =="large" %>

<%= image_tag image.image.url(:large) %><br><br>


<% if @show == true %>
<% if image.user == current_user %>
<%= link_to "edit", edit_user_image_path(current_user, image) %>
<%= link_to "delete", user_image_path(current_user, image), method: :delete, data: {confirm: "Are you sure, bru?"} %>

<% end %>
<br><br>

<% end %>

<strong>Comments:</strong>

<div id="testimonials" class="container spacer ">
  <h2 class="text-center  wowload fadeInUp">Comments</h2>
  <div class="clearfix">    
    <div class="col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">
  	<div id="carousel-testimonials" class="carousel slide testimonails  wowload fadeInRight" data-ride="carousel">
    		<div class="carousel-inner"> 
				<%= render image.comments %>
			</div>		
			</div>					
		</div>
	</div>
</div>


<% @comment = image.comments.new %>
<%= render "comments/form" %>


<% else %>
<figure class="effect-oscar  wowload fadeInUp">
        <img src=<%= image.image.url(:medium) %>/>
        <figcaption>
            <h4><%=link_to image.user.username, user_images_path(image.user)%></h4>
            <p><strong>Caption: </strong><%= captionSend(image) %><br>
            <%=link_to "view", user_image_path(image.user, image)%></p>            
        </figcaption>
</figure>
<% end %>






<% end %>

app/views/images/edit.html.erb
<% @path = user_image_path(current_user, @image) %>

<%= render "form" %>

app/views/images/feed.html.erb
<% @size = "medium" %>
<% @feed = true %>
<div id="works"  class=" clearfix grid">
<%= render @images %>
</div>

app/views/images/hash.html.erb
<h2>Posts with hashtag #<%= @hashtagText %></h2>
<div id="works"  class=" clearfix grid">
<%= render @images %>
</div>

app/views/images/index.html.erb
<h1><%= @user.username %>'s profile:</h1>
<% @size = "medium" %>

<h5>Followers: <%= @user.followers.count %></h5>

<h5>Following: <%= @user.followees.count %></h5>

<h3>Pictures:</h3>
<div id="works"  class=" clearfix grid">
<%= render @images %>
</div>

app/views/images/new.html.erb
<% @path = user_images_path %>
<%= render "form" %>

app/views/images/show.html.erb
<% @size = "large" %>
<% @show = true %>
<%= render @image %>

app/views/layouts/_nav.html.erb
<p>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <br>
  <%= link_to "Your profile", user_images_path(current_user) %> &nbsp;&nbsp;|
  <%= link_to "Feed",  feed_path(current_user)%>&nbsp;&nbsp;|
  <%= link_to "Upload a new picture",  new_user_image_path(current_user)%>&nbsp;&nbsp;|
  <%= link_to "view all users to follow", allusers_path %>
   
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BruGram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
  <!-- Google fonts -->
<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Josefin+Sans:600' rel='stylesheet' type='text/css'>

<!-- font awesome -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<%= render "layouts/nav" %>

<%= yield %>

<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title">Title</h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->    
</div>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/users/_user.html.erb
<%= user.username %> &nbsp;
<%= user.email %> &nbsp;

<% if user!= current_user %>
<% if !current_user.followees.include?(user) %>
<%= link_to "follow", followlinks_path(:followee_id => user), method: :post%>
<% else %>
<%= link_to "unfollow", followlink_path(Followlink.where(user_id: current_user.id, followee_id: user.id)[0]), method: :delete%>
<% end %>
<% else %>
(you, bru...)
<% end %>
<br><br>

app/views/users/index.html.erb
<%= render @users %>

app/views/welcome/index.html.erb
<h1>Welcome to BruGram, bru</h1>

<% if user_signed_in? %>
	<h3>Bru, use nav bar</h3>
<% else %>
	<h3>Bru, log in</h3>
<% end %>